servos:
  conf:
    leg_l_hip: { id: 0, pin: 9, range: [0, 180], start: 40 }
    leg_l_knee: { id: 1, pin: 10, range: [0, 180], start: 10 }
    leg_l_ankle: { id: 2, pin: 11, range: [5, 165], start: 100 }
    leg_r_hip: { id: 3, pin: 6, range: [0, 180], start: 60 }
    leg_r_knee: { id: 4, pin: 7, range: [0, 180], start: 90 }
    leg_r_ankle: { id: 5, pin: 8, range: [10, 180], start: 0 }
    tilt: { id: 6, pin: 2, range: [60, 120], start: 50 }
    pan: { id: 7, pin: 3, range: [30, 150], start: 50 }
  docs:
    description: "The servos module is used to control servos. These are handled by the arduino but positions can be requested by this framework via serial"
    events:
      sub:
        - servo:[identifier]:mvabs:
            description: "Move servo to absolute position."
            args:
              - percentage: integer
        - servo:[identifier]:mv:
            description: "Move servo to relative position."
            args:
              - percentage: integer
              - safe: boolean
      pub:
        - log:
            description: "Send messages to logger."
        - log:error:
            description: "Send error messages to logger."
        - power:use:
            description: "Request power usage."
        - power:release:
            description: "Release power usage."
        - serial:
            description: "Send serial data to arduino."
            args:
              - type: string
              - identifier: integer
              - message: string
